### ISSUE TITLE
Do we need to make caching optional?

### ISSUE THREAD

**Issue by yannikbuhl** [CorrelAid/restatis#23]
We cache all API calls using {memoise}. However, if one does not close her R session frequently, new data will not get fetched. This might be an issue in data with higher frequency or with the publication of the Census results in summer. 

Something we have to think about.

**In any case, we have to emphasise caching more strictly in the documenation and vignettes so users do not get confused.**

**Comment by Vetrarsol** [comment]
My two cents:

1. Caching is generally useful and benefits both the databases (fewer redundant queries) and the user (faster results).
2. There are situations where caching is unwarranted or even harmful, e.g. in #41.
3. Conversely, there are also situations where caching of results across sessions may be useful, such as when handling yearly data not subject to (frequent) revision anymore.

Suggestions:

1. Leave caching on by default.
2. Provide a way of explicitly enabling/disabling caching for the current session.
3. Think about whether the package itself should support caching across sessions (and if so, in which way) or whether this should be left to the user.

Further details for the second suggestion, based on what little of the code I've skimmed:

1. This could be done by adding a `bypass_cache` boolean parameter to functions such as `gen_table` etc.
2. In `zzz.R`, assign different names to the memoised versions of `gen_genesis_api` etc. so that both cached and uncached versions of the low-level database functions are available.
3. Pass the `bypass_cache` parameter to `test_database_functions`  and have it return the cached or uncached database function, as appropriate.

**Comment by yannikbuhl** [comment]
To be honest, I do not think that caching the `gen_list_jobs()` function makes any sense now that I have replicated your example. I will try to remove it entirely for this particular function. Apart from that I continue to think about making caching optional. I am hesitant though about introducing yet another parameter. There's also a way of using an option, but then again that would affect the whole package's functions. I am unsure as to how often one wants to "delete" the cache since many of the data to be retrieved change one a month at most. In this case, simply restarting the R session might be easier.

**Comment by yannikbuhl** [comment]
The problem has been resolved by introducing a `restatis.use_cache` option. There is now a wrapper function gen_api that either uses a cached version or an uncached version depending on whether the user has set `restatis.use_cache = TRUE` or `FALSE`.

This will be available upon the upcoming release.
